# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 877ba6d
_src_path: gh:tfriedel/python-copier-template
author_email: thomas.friedel@gmail.com
author_name: Thomas Friedel
description: Dynalist Export
package_name: dynalist_export
project_name: dynalist_export
python_version: '3.13'
